FROM python:3.11-slim
WORKDIR /app
COPY worker-service/requirements.txt .
RUN pip install --no-cache-dir redis==5.0.0 pymongo==4.7.0 python-dotenv==1.0.0
COPY worker-service/ .
CMD ["python", "-u", "main.py"]