apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-service
  namespace: gridfault
  labels:
    app: inference-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inference-service
  template:
    metadata:
      labels:
        app: inference-service
    spec:
      containers:
        - name: inference-service
          image: sakshishukla10/grid-fault-inference:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: ENV_SERVICE_URL
              value: "http://env-service:7860"
          envFrom:
            - secretRef:
                name: gridfault-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: gridfault
spec:
  selector:
    app: inference-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inference-hpa
  namespace: gridfault
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inference-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70